# Generated by Django 3.0.5 on 2020-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(blank=True, max_length=50, null=True)),
                ('empMobile', models.CharField(blank=True, max_length=50, null=True)),
                ('empEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('postion', models.CharField(blank=True, max_length=50, null=True)),
                ('empCode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
